### PR TITLE
feat: add autorotate

### PR DESCRIPTION
**Pull request by webmarkyn**
Turntable is automatically rotated if `autorotate` prop has `enabled` property set to `true`. Autorotation is disabled as soon as mousedown/keydown events are fired.

### CODE REVIEW

**Comment by nerdyman** [comment]
Thanks for opening this @webmarkyn, it's a great feature! I'll take a look at it today

**Review by nerdyman — CHANGES_REQUESTED** [review]
Thanks for this feature @webmarkyn!

I've left a pretty minor tweak for the `autoRotate` prop in the review.

Also, I think it should continue rotating after the user stops interacting with the component too, what do you reckon?

Example scenario with `autoRotate.disabled: false`:

- Stop autorotation while pointer down 
- Resume autorotation on pointer up

It would be better this way IMO since the default behaviour would always do what the `autoRotate.disabled` prop says rather than only doing it once. This means a developer could choose to disable autorotation if they wanted be adding a `pointerdown` event to the turntable and disable it themselves if thet wanted to.

E.g.

```ts
// Developer can choose to disable autorotation themselves if they want to.
const SomeComponent = () => {
  const [disabled, setDisabled] = useState(false);
  
 const onPointerDown = () => {
   setDisabled(true);
  }


  return (
    <ReactImageTurntable 
      autoRotate={{ disabled }} 
      onPointerDown={onPointerDown}
    />
  );
};
```

**Comment by webmarkyn** [comment]
@nerdyman thanks for the review. Made the changes you requested, please take a look.

**Comment by webmarkyn** [comment]
@nerdyman Hello. Can you check the PR please?

**Comment by nerdyman** [comment]
Hi Mark, unfortunately I got really bad food poisoning over the weekend and
had to go the hospital so I won't be able to review for another day or two.

**Comment by webmarkyn** [comment]
@nerdyman Sorry to hear that. Take care.

**Review by nerdyman — APPROVED** [review]

**Comment by nerdyman** [comment]
Thanks for your work and patience on this @webmarkyn!

**Pull request merged**
